# Generated by Django 3.2.3 on 2021-08-28 15:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('1052fb19-efa2-4a09-aaac-44f25430c72e'), editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30, verbose_name='タイトル')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='価格')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
            ],
            options={
                'db_table': 'book',
            },
        ),
    ]
